### PR TITLE
#14 implementation

### LINKED ISSUE #14: interface for uploading questions as structured text
this should be an interface in the backend. The text format should be that of #26. 
Questions with exactly the same question text should be overridden, the others appended.

### PR DESCRIPTION
**Pull request by pramodbontha**
Added a new interface for admin using react and added Uploading a quiz feature using quiz parser.py
Interface can be accessed through '/admin'. Users only with admin roles can only login into that interface.

### CODE REVIEW

**Review by tillmo — CHANGES_REQUESTED** [review]
When I log into the admin interface, I cannot see any link to the quiz upload.

**Comment by pramodbontha** [comment]
> When I log into the admin interface, I cannot see any link to the quiz upload.

Please check with the front end url ' localhost:3000/admin' . I have created an admin panel in the front end.

**Review by tillmo — CHANGES_REQUESTED** [review]
good, now I see it. When there is an error message, the first lines should be shown. Try e.g. a file where you insert a line "a:answer" at places where it does not belong. Then you should display the message "Wrong line: a:answer", which is the first line of the output. 
In case that there is a duplicate quiz, show the first two lines, e.g.
```
Wrong line: quiz: Video 1-5
duplicate quiz
```

**Comment by tillmo** [comment]
You have misunderstood me. You should **not** add specific code inspecting certain types of errors. The duplicate quiz error is just an example.
You should output the error messages generated by the `read_quiz` function properly. Note that `read_quiz` calls `read_quiz_aux`, catches exceptions, `print`s them, and re-raises them. You probably need a new function that calls `read_quiz_aux`, catches exceptions, and `return`s the error message contained in the exception, but that does not re-raise the exception.

**Comment by pramodbontha** [comment]
As suggested instead re-raising exception I returned them after catching.
@tillmo Could you please let me know if I have to remove the "Wrong Line" for every exception.

Thank you in advance.

**Comment by tillmo** [comment]
You have removed the "Wrong line" info. But you should show it! Sometimes, after "Wrong line", more info is shown. This should also be shown. By contrast, the text of the exception itself is not interesting.

**Comment by tillmo** [comment]
When I submit this file
```
quiz: Video 1-5aa
d: Syntax atomarer Sätze
q: Ist P(f(a),b) ein korrekter atomarer Satz?
j:k
```
I only get
```
NOT NULL constraint failed: QuizBoard_justifications.answer_id
```
On the master branch, I additionally get
```
Wrong line: j:k
```
and this is the line that should be shown, not the other one.

**Review by tillmo — APPROVED** [review]

**Pull request merged**
