### PR TITLE
#105 Added new charts to Overall Statistics

### PR DESCRIPTION
**Pull request by pramodbontha**
Added
1. Total number of participants.
2. Converted integer to float values in average question solved by user chart
3. Integrated users attempted in box plot.
4. A new chart with number of quizzes attempted distribution

### CODE REVIEW

**Comment by tillmo** [comment]
Good. Here are my comments:
* with the real data, the total number of users is 155, but in the diagram "Score Distribution - All Users", the numbers sum up to 92. Where are the remaining users?
* In the diagram "All Users Performance for Every Quiz", please add "(in brackets: number of users)"
* In the diagram "Quizzes Attempts Distribution - All Users", question attempts are shown, not quiz attempts.

**Comment by pramodbontha** [comment]
> * In the diagram "Quizzes Attempts Distribution - All Users", question attempts are shown, not quiz attempts.

@tillmo for the last point in the issue description it is mentioned to show attempted quizzes. I am little confused.
I am making the change as follows
on X axis - number of users
y-axis - number of questions attempted
Could you please correct me if I am wrong here.

Thank you in advance.

**Comment by tillmo** [comment]
Indeed, as you write, the task is to show the attempted quizzes. However, with the current implementation, the attempted questions are shown. But the x axis should show the quizzes, not the questions.

**Comment by pramodbontha** [comment]
> Good. Here are my comments:
> 
> * with the real data, the total number of users is 155, but in the diagram "Score Distribution - All Users", the numbers sum up to 92. Where are the remaining users?

There may be users who just registered and did not participated in any quiz. For this I have added one more text saying "Total participants participated in atleast one quiz" and showing the number of participants.

> * In the diagram "All Users Performance for Every Quiz", please add "(in brackets: number of users)"

As suggested added "number of users" but had to reduce the pagination to 7 as the x-axis labels overlap.

> * In the diagram "Quizzes Attempts Distribution - All Users", question attempts are shown, not quiz attempts.

The implementation shows the quizzes attempted. The query is correct. I have checked the axis labels again and axis data.

image

**Comment by tillmo** [comment]
good.
* please add "(in brackets: number of users)" was meant to appear in the headline of the diagram, not for each data item
* for the real data, the diagram "Quizzes Attempts Distribution - All Users" currently shows 40 items, but there are only 29 quizzes, as the previous diagram shows
Bildschirmfoto von 2020-09-21 23-12-01

**Comment by pramodbontha** [comment]
> good.
> 
> * please add "(in brackets: number of users)" was meant to appear in the headline of the diagram, not for each data item

Added Changes.

> * for the real data, the diagram "Quizzes Attempts Distribution - All Users" currently shows 40 items, but there are only 29 quizzes, as the previous diagram shows
>   Bildschirmfoto von 2020-09-21 23-12-01

For the last graph, the x axis labels are not quiz ids.
I tried to represent the graph as follows
x axis shows the number of quizzes attempts and on y axis shows number of users.
one quiz attempt - 6 users did it
two quizzes attempts - 20 users did it..

We get to know the number of user taken a quiz in box plot graph.

**Comment by tillmo** [comment]
Still, the last graph should have title "Distribution of question attempts", not "quiz attempts". After all, in the data, there are 29 quizzes; hence, a user cannot have attempted 40 quizzes.

Moreover, still I would like to have a graph showing the number of users that have attempted each quiz, even if the box plot already shows this information (note that that the box plot needs to use pagination, while here, a non-paginated graph can be used).

**Comment by pramodbontha** [comment]
> Still, the last graph should have title "Distribution of question attempts", not "quiz attempts". After all, in the data, there are 29 quizzes; hence, a user cannot have attempted 40 quizzes.
> 

I was wrong. There cannot be 40 attempted quiz by 1 user. Made the change to "Distribution of question attempts".

> Moreover, still I would like to have a graph showing the number of users that have attempted each quiz, even if the box plot already shows this information (note that that the box plot needs to use pagination, while here, a non-paginated graph can be used).

Added a quiz attempt chart.

**Comment by tillmo** [comment]
Looks better. Still, the figures do not match. With the real data from the summer semester (I can provide them in anonymous form, if needed), I get that there are 155 users, of which 94 attempted a quiz. Both the box plots and the distribution of quiz attempts for all users show that 164 users attempted quiz 1. This contradicts the number of 94 users who attempted a quiz.

Moreover, the diagram "Distribution of question attempts - All Users" shows that 8 users attempted 1 question. Now for one question, one can get a score of 0, 5 or 10. But in the diagram "Score Distribution - All Users", only 3 users got such scores (1 user got score 0, 2 users got score 10). This does not match.

Bildschirmfoto von 2020-09-26 12-52-39
Bildschirmfoto von 2020-09-26 12-52-46
Bildschirmfoto von 2020-09-26 12-52-49

**Comment by pramodbontha** [comment]
Understood the root cause.  There are multiple entries for a user per quiz. In the current fix, tried to eliminate considering those multiple entries for calculating statistics. All the charts data will be correct.
And changed the questions attempted to quizzes attempted. This data is correct now. 
@tillmo could you please let me know if the graphs are correct now for production data
if there are mistakes, could you please give me the data. I tried to connected to server from my local frontend code, but it is blocking the access because of CORS.

Thank you in advance

**Review by tillmo — APPROVED** [review]
looks good now!

**Pull request merged**
