### PR TITLE
#29, 23 Issue fixes, python dependencies

### PR DESCRIPTION
**Pull request by pramodkumarbontha**
#29 , #23 issue fixes and added requirements.txt file for installing django dependencies at once

### CODE REVIEW

**Comment by pramodkumarbontha** [comment]
Requirements.txt  can used for directly installing all dependencies in one go
python intstall -r requirements.txt will install all dependencies.

I need some help in understanding showing the explanations

I need to show explanation text for only wrong justifications for correct answer?. Will remove the text for correct justification. 
Text for wrong justifications1 

Since all the justifications are wrong for a wrong answer Do I have to show explanation text to those justifications too?
Text for wrong justifications2

Could you please help me understand this @tillmo 

Thanks in advance

**Comment by tillmo** [comment]
please just show the explanation for **one** justification, namely for the justification that has been selected by the user. And do this only if the justification is wrong.

**Comment by jelmd** [comment]
I wonder, how the **requirements.txt** got created. Is it generated? If so, how? I've seen it in other python apps and can conclude, that this does __not__ work and is pure poison!

IMHO it is much much better, and works properly, to have a file like this, but _manually_ maintained. I.e. if one needs a new python package/module, one should manually append it to the file and optionally a version number, if there is a real reason for it.

E.g. if I `find . -type f -name "*.py" -exec grep ^from {} +` in `backend/lqserver/` I do not find any requirement for `asgiref`, `certify`, ... The only requirements I see, are some django and  rest_framework modules. Therefore the file should look like
```
# NOTE: versions are those used in the next LTS release (20.04 alias focal)
django==2.2.11
djangorestframework==3.10.2
django-cors-headers==2.2.0
django-allauth==0.41.0'
django-nested-admin
django-rest-auth
```
Everything else is probably junk: let pip3 resolve the sub dependencies. They can, and will change! So IMHO unless you do not trust pip (which is ok ;-)) and really wanna manage each implicit dependency manually, specifying implicit dependencies is a big harm - you never know, when they change and whether they still have the same dependencies in the future, e.g. they may switch to use another implementation of XY ...

**Comment by pramodkumarbontha** [comment]
@jelmd Hey Jens. Thanks for the detailed information :) . I have made the changes as you suggested.

@tillmo Have the fixed the comments and fixed one more issue #22

**Pull request merged**
