### PR TITLE
#39, #42 fixes

### PR DESCRIPTION
**Pull request by pramodkumarbontha**
Implemented quiz report functionality and requirements mentioned in #39 and #42

### CODE REVIEW

**Comment by pramodkumarbontha** [comment]
@tillmo Thank you for the insights. I will disable the editing of the answers which are submitted so that user cannot edit again.

**Comment by tillmo** [comment]
I think the second option is better - allow modifications of answers and justifications.
You just need to remove the display of the correct answer and justification.
Moreover, the score for giving a correct answer and justification only at the second or third attempt should be lower than that for being correct already in the firs attempt. An easy way of achieving this is giving negative scores for incorrect answers and justifications. Then, you do not need to have a book-keeping of attempts, but only need to sum up scores across different attempts.

**Comment by tillmo** [comment]
> @tillmo Thank you for the insights. I will disable the editing of the answers which are submitted so that user cannot edit again.

OK, that is fine. Then we can realise the other idea later on, if there is time.

**Comment by pramodkumarbontha** [comment]
> > @tillmo Thank you for the insights. I will disable the editing of the answers which are submitted so that user cannot edit again.
> 
> OK, that is fine. Then we can realise the other idea later on, if there is time.

@tillmo Thank you. For now I have disabled selection as a quick fix. I will work on the other idea as separate issue

**Pull request merged**
